### ISSUE TITLE
v3 launch

### ISSUE THREAD

**Issue by pveyes** [traveloka/slack-robot#10]
This is main issue to track v3 launch

Below are the task needed to launch v3
- [x] #6 Built-in help generator 
- [x] #11 Provide replacement to `robot.brain`
- [x] #17 Provide replacement to `listener.acl`
- [x] #14 Fixed emoji formatting
- [x] #15 Plugin init limit
- [x] #16 Distinct ignored channel
- [x] #13 Final testing
